/**  USERS **/
export const SAVE_USER = 'USER/SAVE_USER';

/** ROOT **/
export const SET_LOADING = 'ROOT/SET_LOADING';
export const SET_APP_READY = 'ROOT/SET_APP_READY';
export const SHOW_ALERT = 'ROOT/SHOW_ALERT';
export const SET_MODALIDADES = 'ROOT/SET_MODALIDADES';
export const SET_ESTADO_CIVIL = 'ROOT/SET_ESTADO_CIVIL';
export const SET_NIVEL_ACADEMICO = 'ROOT/SET_NIVEL_ACADEMICO';
export const SET_PROVINCIAS = 'ROOT/SET_PROVINCIAS';
export const SET_GENEROS = 'ROOT/SET_GENEROS';
export const SET_LISTA_PERMISOS = 'ROOT/SET_LISTA_PERMISOS';
export const SET_LISTA_ROLES = 'ROOT/SET_LISTA_ROLES';
export const SET_LISTA_NACIONALIDADES = 'ROOT/SET_LISTA_NACIONALIDADES';
export const SET_LISTA_TIPOS_ID = 'ROOT/SET_LISTA_TIPOS_ID';
export const SET_TIPOS_POBREZA = 'ROOT/SET_TIPOS_POBREZA';
export const SET_GRADOS_DEPENDENCIA = 'ROOT/SET_GRADOS_DEPENDENCIA';
export const SET_PROGRAMAS = 'ROOT/SET_PROGRAMAS';
export const SET_LISTA_TIPOS_DOC = 'ROOT/SET_LISTA_TIPOS_DOC';
export const SET_LISTA_DOCUMENTOS = 'ROOT/SET_LISTA_DOCUMENTOS';
export const LOAD_LISTA_DOCUMENTOS = 'ROOT/LOAD_LISTA_DOCUMENTOS';
export const SET_NOTIFICATIONS = 'ROOT/SET_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS = 'ROOT/LOAD_NOTIFICATIONS';
export const SEND_NEW_FILE = 'ROOT/SEND_NEW_FILE';
export const ACEPTAR_DOCUMENTO = 'ROOT/ACEPTAR_DOCUMENTO';
export const RECHAZAR_DOCUMENTO = 'ROOT/RECHAZAR_DOCUMENTO';
export const LOAD_ORGS = 'ROOT/LOAD_ORGS';

export const SAVE_FILTER_VALUE = 'ROOT/SAVE_FILTER_VALUE';


/** INITIAL PAGE */
export const SAVE_BLOG_PREVIEW = 'INITIAL_PAGE/SAVE_BLOG_PREVIEW';
export const SAVE_PENDING_DOCS = 'INITIAL_PAGE/SAVE_PENDING_DOCS';
export const CHANGE_SOURCE_SELECTED = 'INITIAL_PAGE/CHANGE_SOURCE_SELECTED';
export const SAVE_LISTADO_PAM = 'INITIAL_PAGE/SAVE_LISTADO_PAM';
export const CHANGE_PAM_STATUS = 'INITIAL_PAGE/CHANGE_PAM_STATUS';
export const REFRESH_LISTADO_PAM = 'INITIAL_PAGE/REFRESH_LISTADO_PAM';
export const SAVE_TABLE_STATE = 'INITIAL_PAGE/SAVE_TABLE_STATE';
export const SET_INITIAL_PAGE_READY = 'INITIAL_PAGE/READY';


/** LAWS PAGE **/
export const SAVE_LAWS_LIST = 'LAWS_PAGE/SAVE_LAWS_LIST';
export const DELETE_LAW = 'LAWS_PAGE/DELETE_LAW';

/** ORGS PAGE **/
export const SAVE_ORGS_LIST = 'ORGANIZATIONS_PAGE/SAVE_ORGS_LIST';
export const DELETE_ORG = 'ORGANIZATIONS_PAGE/DELETE_ORG';
export const SAVE_FILTER_VALUE_ORGS = 'ORGANIZATIONS_PAGE/SAVE_FILTER_VALUE';

/** GEOLOCATION PAGE **/
export const SAVE_GEO_LIST = 'GEOLOCATION_PAGE/SAVE_GEO_LIST';

/** USERS PAGE **/
export const SAVE_USERS_LIST = 'USERS_PAGE/SAVE_USERS_LIST';
export const DELETE_USER = 'USERS_PAGE/DELETE_USER';
export const REFRESH_LISTADO_USUARIOS = 'USERS_PAGE/REFRESH_LISTADO_USUARIOS';

/** PAM PAGE **/
export const SAVE_PRESUPUESTO_ORDINARIO_LIST = 'PAM_PAGE/SAVE_PRESUPUESTO_ORDINARIO_LIST';
export const SAVE_PRESUPUESTO_EXTRAORDINARIO_LIST = 'PAM_PAGE/SAVE_PRESUPUESTO_EXTRAORDINARIO_LIST';
export const SAVE_MEDICION_UNO_LIST = 'PAM_PAGE/SAVE_MODALIDAD_UNO_LIST';
export const SAVE_ACTIVOS_POSIBLES_BENEFICIARIOS_LIST = 'PAM_PAGE/SAVE_ACTIVOS_POSIBLES_BENEFICIARIOS_LIST';

/** EXPIRATIONS **/
export const SET_EXPIRATION_PAGE_READY = 'EXPIRATIONS_PAGE/SET_EXPIRATION_PAGE_READY';
export const SET_SELECTED_STATUS = 'EXPIRATIONS_PAGE/SET_SELECTED_STATUS'

/** ROLES **/

export const ROLE_ADMIN = {id: '1', role: 'ADMIN'};
export const ROLE_ORG = {id: '2', role: 'OBS/GL'};

/** COOKIES **/
export const USERID_STORE_KEY = 'user_id';
export const USER_ROLE_STORE_KEY = 'user_role';
export const TOKEN_STORE_KEY = 'authorization_token';

/** MAPS **/
export const GOOGLE_MAP_API_KEY = 'AIzaSyAdVwEohok7Q6HzafZrxdSr0TN85HTymgY';
